[workspace]
members = [
  "git-utils",
  "git-default-branch",
]
resolver = "2"

[workspace.dependencies]
env_logger = "0.10"
git2 = "0.18"
log = "0.4"

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"
